"""
================================================================================
HMATS v6.1.0 - Shadow Ledger JSONL Writer
================================================================================
Purpose: Persistent audit trail for all trading activity

Writes to JSONL (one JSON object per line) for:
- Easy append-only writes
- Simple grep/search
- Line-by-line streaming read
- No corruption on crash

Entry Types:
- INTENT: Trading intent generated by decision engine
- ORDER: Order submitted to exchange
- FILL: Order fill received
- POSITION: Position change
- RISK_EVENT: Risk controller event
- GATE_REJECT: Trade gate rejection
- HUMAN_OVERRIDE: Human intervention

================================================================================
"""

import json
import logging
import threading
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, Optional, List, Set
from dataclasses import dataclass, asdict
from enum import Enum

logger = logging.getLogger(__name__)


class LedgerEntryType(Enum):
    """Types of ledger entries."""
    INTENT = "INTENT"
    ORDER = "ORDER"
    FILL = "FILL"
    POSITION = "POSITION"
    RISK_EVENT = "RISK_EVENT"
    GATE_REJECT = "GATE_REJECT"
    HUMAN_OVERRIDE = "HUMAN_OVERRIDE"
    SYSTEM_EVENT = "SYSTEM_EVENT"


@dataclass
class LedgerRecord:
    """A single ledger record."""
    timestamp: str
    entry_type: str
    asset: str
    data: Dict[str, Any]
    tick_id: int = 0
    session_id: str = ""
    
    def to_json(self) -> str:
        return json.dumps(asdict(self), default=str)


class ShadowLedgerWriter:
    """
    JSONL writer for shadow ledger audit trail.
    
    Features:
    - Append-only writes (crash safe)
    - Automatic rotation by date
    - In-memory buffer with periodic flush
    - Thread-safe
    
    Usage:
        writer = ShadowLedgerWriter("data/shadow_ledger")
        writer.record_intent(asset="SOL", direction=-1, size=0.5, ...)
        writer.record_order(asset="SOL", order_id="ABC123", ...)
        writer.flush()
    """
    
    FLUSH_INTERVAL_SECONDS = 30
    BUFFER_SIZE = 100
    
    def __init__(
        self,
        output_dir: str = "data/shadow_ledger",
        session_id: str = None,
        auto_flush: bool = True,
    ):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        self.session_id = session_id or datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        self._buffer: List[LedgerRecord] = []
        self._lock = threading.Lock()
        self._tick_id = 0
        self._entry_count = 0
        self._last_flush_time = time.time()
        self._session_fill_count = 0
        self._session_fill_counts: Dict[str, int] = {}
        self._session_last_fill_at: Optional[str] = None
        self._session_last_fill_at_by_asset: Dict[str, str] = {}

        # [P85 architectural follow-up — 2026-06-09] In-process set of
        # exchange order_ids the ledger has tracked as outstanding. Used
        # by startup_reconciler to classify open exchange orders as
        # known-vs-orphan. record_order adds; record_fill removes; the
        # explicit release_order method handles cancels. The set is NOT
        # authoritative on its own at startup — callers MUST first call
        # replay_frozen_allocations_from_jsonl() to seed from history,
        # otherwise a fresh process would see every legitimate order as
        # orphan. The startup_reconciler's defensive `getattr` remains
        # as belt-and-suspenders for older module versions and the
        # not-yet-replayed window.
        self.frozen_allocations: Set[str] = set()
        self._frozen_allocations_replayed: bool = False

        # [P139 belt-and-suspenders — 2026-06-10] Set of order_ids that
        # already have a recorded FILL. Defense-in-depth against the
        # idempotency-cache phantom-fill bug: even if a caller in
        # execute_intent_v2 forgets to check is_cached_idempotent, the
        # second record_fill() with the same order_id is rejected here
        # with a one-shot WARN per order_id. Replay from JSONL on
        # startup so a fresh process doesn't accept duplicates that
        # were already recorded by the prior process.
        self._recorded_fill_order_ids: Set[str] = set()
        self._duplicate_fill_warned: Set[str] = set()

        # Current file handle
        self._current_date: Optional[str] = None
        self._file_handle = None
        
        # Auto-flush in background
        self._auto_flush = auto_flush
        self._running = False
        self._flush_thread: Optional[threading.Thread] = None
        
        if auto_flush:
            self._start_auto_flush()
        
        logger.info(f"[ShadowLedgerWriter] Initialized: {self.output_dir}, session={self.session_id}")
    
    def _start_auto_flush(self):
        """Start background flush thread."""
        self._running = True
        self._flush_thread = threading.Thread(target=self._flush_loop, daemon=True)
        self._flush_thread.start()
    
    def _flush_loop(self):
        """Background flush loop."""
        while self._running:
            time.sleep(self.FLUSH_INTERVAL_SECONDS)
            try:
                self.flush()
            except Exception as e:
                logger.error(f"[ShadowLedger] Flush error: {e}")
    
    def _get_output_file(self) -> Path:
        """Get output file for today."""
        today = datetime.now(timezone.utc).strftime("%Y%m%d")
        return self.output_dir / f"ledger_{today}.jsonl"
    
    def _ensure_file_open(self):
        """Ensure file is open for today."""
        today = datetime.now(timezone.utc).strftime("%Y%m%d")
        
        if self._current_date != today:
            # Close old file
            if self._file_handle:
                self._file_handle.close()
            
            # Open new file
            output_path = self._get_output_file()
            self._file_handle = open(output_path, 'a', encoding='utf-8')
            self._current_date = today
            logger.info(f"[ShadowLedger] Opened: {output_path}")
    
    def _record(
        self,
        entry_type: LedgerEntryType,
        asset: str,
        data: Dict[str, Any],
    ):
        """Internal record method."""
        record = LedgerRecord(
            timestamp=datetime.now(timezone.utc).isoformat(),
            entry_type=entry_type.value,
            asset=asset,
            data=data,
            tick_id=self._tick_id,
            session_id=self.session_id,
        )
        
        with self._lock:
            if entry_type == LedgerEntryType.FILL:
                self._session_fill_count += 1
                self._session_fill_counts[asset] = int(self._session_fill_counts.get(asset, 0) or 0) + 1
                self._session_last_fill_at = record.timestamp
                self._session_last_fill_at_by_asset[asset] = record.timestamp
            self._buffer.append(record)
            self._entry_count += 1
            
            # Auto-flush if buffer full
            if len(self._buffer) >= self.BUFFER_SIZE:
                self._flush_buffer()
    
    def _flush_buffer(self):
        """Flush buffer to disk (must hold lock)."""
        if not self._buffer:
            return
        
        try:
            self._ensure_file_open()
            
            for record in self._buffer:
                self._file_handle.write(record.to_json() + "\n")
            
            self._file_handle.flush()
            self._buffer.clear()
            self._last_flush_time = time.time()
            
        except Exception as e:
            logger.error(f"[ShadowLedger] Write error: {e}")
    
    def set_tick_id(self, tick_id: int):
        """Set current tick ID."""
        self._tick_id = tick_id
    
    # =========================================================================
    # PUBLIC RECORDING METHODS
    # =========================================================================
    
    def record_intent(
        self,
        asset: str,
        direction: int,
        size: float,
        is_entry: bool,
        confidence: float,
        regime: str,
        mode: str,
        reason: str = "",
        extra: Dict = None,
    ):
        """Record trading intent."""
        self._record(
            LedgerEntryType.INTENT,
            asset,
            {
                "direction": direction,
                "size": size,
                "is_entry": is_entry,
                "confidence": confidence,
                "regime": regime,
                "mode": mode,
                "reason": reason,
                **(extra or {}),
            }
        )
    
    def record_order(
        self,
        asset: str,
        order_id: str,
        side: str,
        size: float,
        order_type: str,
        price: float = None,
        status: str = "SUBMITTED",
        extra: Dict = None,
    ):
        """Record order submission."""
        # [P85 architectural] Track the order_id so startup_reconciler
        # can distinguish ours-vs-orphan. Guard against falsy ids; some
        # paper-mode paths submit synthetic order_ids that are None.
        if order_id:
            with self._lock:
                self.frozen_allocations.add(str(order_id))
        self._record(
            LedgerEntryType.ORDER,
            asset,
            {
                "order_id": order_id,
                "side": side,
                "size": size,
                "order_type": order_type,
                "price": price,
                "status": status,
                **(extra or {}),
            }
        )
    
    def record_fill(
        self,
        asset: str,
        order_id: str,
        fill_id: str,
        side: str,
        size: float,
        price: float,
        fee: float = 0.0,
        fee_currency: str = "USD",
        realized_pnl: float = 0.0,
        extra: Dict = None,
    ) -> bool:
        """Record order fill with optional realized PnL.

        Returns True if recorded, False if rejected as duplicate (P139).
        """
        # [P139 belt-and-suspenders — 2026-06-10] Refuse to record a
        # duplicate FILL for an order_id we've already seen. Without
        # this guard, the idempotency-cache phantom-fill bug (see
        # CLAUDE.md P139 + execution_manager.execute_order:1180) would
        # silently inflate paper_positions every tick. WARN once per
        # order_id so repeated dups don't spam, but the first one is
        # visible. Falsy order_ids skip the dedup (paper-mode synthetic
        # ids that legitimately can collide).
        _oid_str = str(order_id) if order_id else ""
        if _oid_str:
            with self._lock:
                if _oid_str in self._recorded_fill_order_ids:
                    if _oid_str not in self._duplicate_fill_warned:
                        self._duplicate_fill_warned.add(_oid_str)
                        logger.warning(
                            f"[ShadowLedger] record_fill duplicate REJECTED: "
                            f"order_id={_oid_str!r} already has a FILL record "
                            f"(asset={asset}, side={side}, size={size}). "
                            f"Likely cause: execute_order's idempotency-cache "
                            f"path returned the cached order_id and the caller "
                            f"did not check is_cached_idempotent. See P139."
                        )
                    return False
                self._recorded_fill_order_ids.add(_oid_str)

        # [P85 architectural] Order is filled — release the tracking slot
        # so it's not counted as outstanding by future reconciler runs.
        # Partial fills: this releases on FIRST fill. Acceptable trade-off
        # since the reconciler's purpose is detecting *unknown* orders,
        # not tracking partial-fill remainders. discard() is no-op on miss.
        if order_id:
            with self._lock:
                self.frozen_allocations.discard(str(order_id))
        self._record(
            LedgerEntryType.FILL,
            asset,
            {
                "order_id": order_id,
                "fill_id": fill_id,
                "side": side,
                "size": size,
                "price": price,
                "fee": fee,
                "fee_currency": fee_currency,
                "notional": size * price,
                "realized_pnl": realized_pnl,
                **(extra or {}),
            }
        )
        return True

    def release_order(self, order_id: str) -> bool:
        """[P85 architectural] Explicitly release an order_id from the
        frozen_allocations set without recording a FILL.

        Use when an order is cancelled, expired, or rejected — i.e.
        cases where there's no fill but the order is no longer
        outstanding. Returns True if the id was tracked + removed,
        False if it was never tracked or already released.
        """
        if not order_id:
            return False
        with self._lock:
            _had = str(order_id) in self.frozen_allocations
            self.frozen_allocations.discard(str(order_id))
            return _had

    def replay_frozen_allocations_from_jsonl(self, days_back: int = 2) -> int:
        """[P85 architectural] Seed frozen_allocations from recent JSONL
        history so a fresh process restart doesn't classify legitimate
        open exchange orders as orphan.

        Replay walks the last `days_back` daily ledger files, adding
        ORDER entries' order_ids to the set and removing them on
        subsequent FILL entries with the same id. The result is the
        net "still outstanding from history" set. The reconciler should
        call this BEFORE classifying exchange orders.

        Returns: count of order_ids in the set after replay.

        Failure mode: any file read error logs WARN and continues —
        partial replay is better than crashing the reconciler. The
        startup_reconciler's defensive `getattr` still catches the
        case where this method itself is missing on older modules.
        """
        from datetime import timedelta
        now = datetime.now(timezone.utc)
        seeded: Set[str] = set()
        # [P139 belt-and-suspenders] Seed the FILL-dedup set in the same
        # JSONL pass — every order_id that ever had a FILL record goes
        # into _recorded_fill_order_ids. A fresh process restart then
        # rejects re-recording any of those, even if the caller's P139
        # layer-1 short-circuit is missing or buggy.
        seen_fill_oids: Set[str] = set()
        for d in range(days_back, -1, -1):  # oldest -> newest
            day = (now - timedelta(days=d)).strftime("%Y%m%d")
            path = self.output_dir / f"ledger_{day}.jsonl"
            if not path.exists():
                continue
            try:
                with open(path, "r", encoding="utf-8") as fh:
                    for line in fh:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            obj = json.loads(line)
                        except json.JSONDecodeError:  # noqa: silent-swallow
                            # JSONL may have a truncated last line from a
                            # SIGKILL on the prior process. Skip and continue
                            # the replay rather than abort — partial replay
                            # is better than no replay.
                            continue
                        entry_type = obj.get("entry_type")
                        data = obj.get("data") or {}
                        oid = data.get("order_id")
                        if not oid:
                            continue
                        if entry_type == LedgerEntryType.ORDER.value:
                            seeded.add(str(oid))
                        elif entry_type == LedgerEntryType.FILL.value:
                            seeded.discard(str(oid))
                            seen_fill_oids.add(str(oid))
            except Exception as e:
                logger.warning(
                    f"[ShadowLedgerWriter] replay_frozen_allocations: "
                    f"failed reading {path.name} ({type(e).__name__}: {e}); "
                    f"continuing with partial replay."
                )
        with self._lock:
            # Union with anything already tracked in-process (don't clobber
            # orders submitted between __init__ and replay).
            self.frozen_allocations |= seeded
            self._recorded_fill_order_ids |= seen_fill_oids
            self._frozen_allocations_replayed = True
            count = len(self.frozen_allocations)
            fill_count = len(self._recorded_fill_order_ids)
        logger.info(
            f"[ShadowLedgerWriter] replay_frozen_allocations: seeded "
            f"{count} outstanding order(s) + {fill_count} already-filled "
            f"order_id(s) for FILL-dedup (P139) from last {days_back+1} "
            f"day(s) of JSONL."
        )
        return count
    
    def record_position_change(
        self,
        asset: str,
        old_size: float,
        new_size: float,
        old_direction: int,
        new_direction: int,
        realized_pnl: float = 0.0,
        reason: str = "",
        extra: Dict = None,
    ):
        """Record position change."""
        self._record(
            LedgerEntryType.POSITION,
            asset,
            {
                "old_size": old_size,
                "new_size": new_size,
                "old_direction": old_direction,
                "new_direction": new_direction,
                "realized_pnl": realized_pnl,
                "reason": reason,
                **(extra or {}),
            }
        )
    
    def record_risk_event(
        self,
        asset: str,
        event_type: str,
        description: str,
        risk_state: str,
        details: Dict = None,
    ):
        """Record risk controller event."""
        self._record(
            LedgerEntryType.RISK_EVENT,
            asset,
            {
                "event_type": event_type,
                "description": description,
                "risk_state": risk_state,
                "details": details or {},
            }
        )
    
    def record_gate_rejection(
        self,
        asset: str,
        direction: int,
        size: float,
        rejection_reason: str,
        gate_details: Dict = None,
    ):
        """Record trade gate rejection."""
        self._record(
            LedgerEntryType.GATE_REJECT,
            asset,
            {
                "direction": direction,
                "size": size,
                "rejection_reason": rejection_reason,
                "gate_details": gate_details or {},
            }
        )
    
    def record_human_override(
        self,
        override_type: str,
        value: Any,
        reason: str,
        duration_hours: float = 0.0,
    ):
        """Record human override event."""
        self._record(
            LedgerEntryType.HUMAN_OVERRIDE,
            "SYSTEM",
            {
                "override_type": override_type,
                "value": value,
                "reason": reason,
                "duration_hours": duration_hours,
            }
        )
    
    def record_system_event(
        self,
        event_type: str,
        description: str,
        details: Dict = None,
    ):
        """Record system event."""
        self._record(
            LedgerEntryType.SYSTEM_EVENT,
            "SYSTEM",
            {
                "event_type": event_type,
                "description": description,
                "details": details or {},
            }
        )
    
    # =========================================================================
    # CONTROL METHODS
    # =========================================================================
    
    def flush(self):
        """Flush buffer to disk."""
        with self._lock:
            self._flush_buffer()
    
    def close(self):
        """Close writer."""
        self._running = False
        
        if self._flush_thread:
            self._flush_thread.join(timeout=5)
        
        self.flush()
        
        if self._file_handle:
            self._file_handle.close()
            self._file_handle = None
        
        logger.info(f"[ShadowLedger] Closed. Total entries: {self._entry_count}")
    
    def get_stats(self) -> Dict:
        """Get writer statistics."""
        with self._lock:
            return {
                "session_id": self.session_id,
                "output_dir": str(self.output_dir),
                "entry_count": self._entry_count,
                "buffer_size": len(self._buffer),
                "current_tick": self._tick_id,
                "last_flush_time": self._last_flush_time,
                "session_fill_count": self._session_fill_count,
                "session_last_fill_at": self._session_last_fill_at,
            }

    def get_session_fill_summary(self, asset: Optional[str] = None) -> Dict[str, Any]:
        """Return in-memory fill counters for the current session."""
        with self._lock:
            if asset:
                return {
                    "session_id": self.session_id,
                    "asset": asset,
                    "count": int(self._session_fill_counts.get(asset, 0) or 0),
                    "last_fill_at": self._session_last_fill_at_by_asset.get(asset),
                }

            return {
                "session_id": self.session_id,
                "count": int(self._session_fill_count or 0),
                "counts_by_asset": dict(self._session_fill_counts),
                "last_fill_at": self._session_last_fill_at,
                "last_fill_at_by_asset": dict(self._session_last_fill_at_by_asset),
            }
    
    def __enter__(self):
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()


# =============================================================================
# READER UTILITY
# =============================================================================

class ShadowLedgerReader:
    """
    Reader for shadow ledger JSONL files.
    
    Usage:
        reader = ShadowLedgerReader("data/shadow_ledger")
        entries = reader.read_date("2026-01-26")
        recent = reader.get_recent(100)
    """
    
    def __init__(self, ledger_dir: str = "data/shadow_ledger"):
        self.ledger_dir = Path(ledger_dir)
    
    def read_date(self, date_str: str) -> List[Dict]:
        """Read entries for a specific date (YYYYMMDD or YYYY-MM-DD)."""
        date_str = date_str.replace("-", "")
        file_path = self.ledger_dir / f"ledger_{date_str}.jsonl"
        
        if not file_path.exists():
            return []
        
        entries = []
        with open(file_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        entries.append(json.loads(line))
                    except json.JSONDecodeError:
                        continue
        
        return entries
    
    def get_recent(self, limit: int = 100) -> List[Dict]:
        """Get most recent entries across all files."""
        # Get all ledger files sorted by date desc
        files = sorted(
            self.ledger_dir.glob("ledger_*.jsonl"),
            reverse=True
        )
        
        entries = []
        for file_path in files:
            with open(file_path, 'r', encoding='utf-8') as f:
                file_entries = []
                for line in f:
                    line = line.strip()
                    if line:
                        try:
                            file_entries.append(json.loads(line))
                        except json.JSONDecodeError:
                            continue
                
                # Add newest first
                entries.extend(reversed(file_entries))
                
                if len(entries) >= limit:
                    break
        
        return entries[:limit]
    
    def filter_by_asset(self, entries: List[Dict], asset: str) -> List[Dict]:
        """Filter entries by asset."""
        return [e for e in entries if e.get("asset") == asset]
    
    def filter_by_type(self, entries: List[Dict], entry_type: str) -> List[Dict]:
        """Filter entries by type."""
        return [e for e in entries if e.get("entry_type") == entry_type]
    
    def get_summary(self, entries: List[Dict]) -> Dict:
        """Get summary statistics from entries."""
        if not entries:
            return {}
        
        by_type = {}
        by_asset = {}
        
        for e in entries:
            entry_type = e.get("entry_type", "UNKNOWN")
            asset = e.get("asset", "UNKNOWN")
            
            by_type[entry_type] = by_type.get(entry_type, 0) + 1
            by_asset[asset] = by_asset.get(asset, 0) + 1
        
        # Calculate PnL and fees from fills
        total_realized_pnl = 0.0
        total_fees = 0.0
        fills = [e for e in entries if e.get("entry_type") == "FILL"]
        for fill in fills:
            data = fill.get("data", {})
            total_realized_pnl += data.get("realized_pnl", 0.0)
            total_fees += data.get("fee", 0.0)

        return {
            "total_entries": len(entries),
            "by_type": by_type,
            "by_asset": by_asset,
            "fills_count": len(fills),
            "total_realized_pnl": total_realized_pnl,
            "total_fees": total_fees,
            "net_pnl": total_realized_pnl - total_fees,
            "time_range": {
                "first": entries[-1].get("timestamp") if entries else None,
                "last": entries[0].get("timestamp") if entries else None,
            }
        }

    def summarize_fills_since(
        self,
        start_dt: datetime,
        *,
        end_dt: Optional[datetime] = None,
    ) -> Dict[str, Any]:
        """Summarize fill activity in a rolling wall-clock window."""
        if end_dt is None:
            end_dt = datetime.now(timezone.utc)

        counts_by_asset: Dict[str, int] = {}
        last_fill_at: Optional[str] = None
        last_fill_at_by_asset: Dict[str, str] = {}
        fill_count = 0

        for file_path in sorted(self.ledger_dir.glob("ledger_*.jsonl")):
            try:
                with open(file_path, "r", encoding="utf-8") as handle:
                    for line in handle:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            entry = json.loads(line)
                        except json.JSONDecodeError:
                            continue
                        if str(entry.get("entry_type", "")).upper() != LedgerEntryType.FILL.value:
                            continue
                        raw_ts = str(entry.get("timestamp", "") or "")
                        try:
                            entry_dt = datetime.fromisoformat(raw_ts.replace("Z", "+00:00"))
                        except ValueError:
                            continue
                        if entry_dt.tzinfo is None:
                            entry_dt = entry_dt.replace(tzinfo=timezone.utc)
                        if entry_dt < start_dt or entry_dt > end_dt:
                            continue
                        asset = str(entry.get("asset", "") or "").upper()
                        fill_count += 1
                        counts_by_asset[asset] = int(counts_by_asset.get(asset, 0) or 0) + 1
                        last_fill_at = raw_ts
                        last_fill_at_by_asset[asset] = raw_ts
            except OSError:
                continue

        return {
            "count": fill_count,
            "counts_by_asset": counts_by_asset,
            "last_fill_at": last_fill_at,
            "last_fill_at_by_asset": last_fill_at_by_asset,
        }


# =============================================================================
# SINGLETON
# =============================================================================

_ledger_writer: Optional[ShadowLedgerWriter] = None
_ledger_lock = threading.Lock()


def get_shadow_ledger_writer(
    output_dir: str = "data/shadow_ledger",
    session_id: str = None,
) -> ShadowLedgerWriter:
    """Get singleton shadow ledger writer."""
    global _ledger_writer
    if _ledger_writer is None:
        with _ledger_lock:
            if _ledger_writer is None:
                _ledger_writer = ShadowLedgerWriter(
                    output_dir=output_dir,
                    session_id=session_id,
                )
    return _ledger_writer


def close_shadow_ledger():
    """Close singleton writer."""
    global _ledger_writer
    with _ledger_lock:
        if _ledger_writer:
            _ledger_writer.close()
            _ledger_writer = None


if __name__ == "__main__":
    # Test
    with ShadowLedgerWriter("data/test_ledger", session_id="TEST") as writer:
        writer.set_tick_id(1)
        writer.record_intent(
            asset="SOL",
            direction=-1,
            size=0.5,
            is_entry=True,
            confidence=0.75,
            regime="MODERATE_BEAR",
            mode="NORMAL",
            reason="Short signal from quant",
        )
        writer.record_order(
            asset="SOL",
            order_id="TEST001",
            side="sell",
            size=0.5,
            order_type="limit",
            price=102.5,
        )
        writer.record_fill(
            asset="SOL",
            order_id="TEST001",
            fill_id="FILL001",
            side="sell",
            size=0.5,
            price=102.45,
            fee=0.13,
        )
        writer.flush()
        
        print("Stats:", writer.get_stats())
    
    # Read back
    reader = ShadowLedgerReader("data/test_ledger")
    recent = reader.get_recent(10)
    print("\nRecent entries:", len(recent))
    for entry in recent:
        print(f"  {entry['timestamp']} | {entry['entry_type']} | {entry['asset']}")
